https://replit.com/@Luisa-Fernan219/examen2#main.py 

tipo_tarea <= input("ingresa el tipo de tarea") 
#tipo de tarea,descanso,estudio,deportes 
hora_actual = input("hora actual")
#debe estar en 24 horas
plan_semana = input("los dias de la semana")
#lasw actividades en la semana 
elif 1 < hora_actual <= 5 and tipo_tarea == "debes estar dormido":
elif 5 < hora_actual < 14 and tipo_tarea == "debes estar en clase":
if 14 < hora_actual < 22 and tipo_tarea == "puedes hacer tareas"
if 18 < hora_actual < 22 and tipo_tarea == "descanso":
print("ademas de tomar una siesta puedes comenzar a realizar tus tareas")
